name: Generate RSS Feed

on:
  schedule:
    - cron: '0-59/10 1 * * *'  # Runs every 10 minutes on 8am UTC+7 time
  workflow_dispatch:

jobs:
  build-rss:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright browsers
        run: playwright install
      - name: Generate RSS feed
        run: python rss_generator.py
        env: 
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
      # Commit all changed files back to the repository
      - name: Get current date and time
        id: get_date
        run: echo "CURRENT_TIME=$(date '+%Y/%m/%dT%H:%M:%S')" >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto Generate RSS Feed - ${{ env.CURRENT_TIME }}"
